# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required

services:
  vote:
    build: ./vote
    image: sedjro/voting-app:vote-1
    # use python rather than gunicorn for local dev
    # command: python app.py
    # depends_on:
    #   redis:
    #     condition: service_healthy
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    # volumes:
    #  - //wsl$//Ubuntu-22.04//root//enock//votingPlatform//vote:/app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier
    env_file:
      - .env

  result:
    build: ./result
    image: sedjro/voting-app:result-1
    # use nodemon rather than node for local dev
    # entrypoint: nodemon server.js
    # depends_on:
    #   db:
    #     condition: service_healthy 
    # volumes:
    #   - //wsl$//Ubuntu-22.04//root//enock//votingPlatform//result:/app
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier
    env_file:
      - .env

  worker:
    build:
      context: ./worker
    image: sedjro/voting-app:worker-1
    # depends_on:
    #   redis:
    #     condition: service_healthy 
    #   db:
    #     condition: service_healthy 
    networks:
      - back-tier
    env_file:
      - .env

  redis:
    image: redis:alpine
    # volumes:
    #   - "//wsl$//Ubuntu-22.04//root//enock//votingPlatform//healthchecks:/healthchecks"
    # healthcheck:
    #   test: /healthchecks/redis.sh
    #   interval: "5s"
    networks:
      - back-tier

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    #   - "//wsl$//Ubuntu-22.04//root//enock//votingPlatform//healthchecks:/healthchecks"
    # healthcheck:
    #   test: /healthchecks/postgres.sh
    #   interval: "5s"
    networks:
      - back-tier

  # this service runs once to seed the database with votes
  # it won't run unless you specify the "seed" profile
  # docker compose --profile seed up -d
  seed:
    build: ./seed-data
    profiles: ["seed"]
    depends_on:
      vote:
        condition: service_healthy 
    networks:
      - front-tier
    restart: "no"

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
