apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: sedjro/voting-app:result-1
        name: result
        ports:
        - containerPort: 80
          name: result
        env:
          - name: DB_URI
            value: "postgres://postgres:lsDiizBorqJtmI4Y@eks-poc.cvtt5zpyjls7.eu-north-1.rds.amazonaws.com/postgres"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"