apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
spec:
  type: ClusterIP
  ports:
  - name: vote
    port: 80
    targetPort: 80
    # nodePort: 31000
  selector:
    app: vote
  
