apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: sedjro/voting-app:vote-1
        name: vote
        ports:
        - containerPort: 80
          name: vote
        env:
          - name: RD_URL
            value: "tf-redis-cluster.k3siua.clustercfg.eun1.cache.amazonaws.com"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"