apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: sedjro/voting-app:vote-1
        name: vote
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: vote
        env:
          - name: REDIS_CLUSTER_ENDPOINT
            value: "xxx.xxx.clustercfg.eun1.cache.amazonaws.com"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"