apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: sedjro/voting-app:worker-1
        name: worker
        env:
          - name: RD_URL
            value: "tf-redis-cluster.k3siua.clustercfg.eun1.cache.amazonaws.com"
          - name: DB_PARAMS
            value: "Server=eks-poc.cvtt5zpyjls7.eu-north-1.rds.amazonaws.com;Username=postgres;Password=lsDiizBorqJtmI4Y;"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
