apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: dockersamples/examplevotingapp_worker
        name: worker
        env:
          - name: RD_URL
            value: "xxx.xxx.clustercfg.eun1.cache.amazonaws.com"
          - name: DB_PARAMS
            value: "Server=eks-poc.url;Username=postgres;Password=postgres;"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
